template+nvim

diff --git a/script/crun b/script/crun
--- a/script/crun
+++ b/script/crun
@@ -1,17 +1,23 @@
 #!/bin/bash
 
-# a build and run script for c-like language. the script expect a build.sh file
-# under current directory which also generate a main executable file under the
-# same directory.
+# a build and run script for very specific project setup structure, that there
+# should have a build.sh executable file, and then after successfully execute
+# the script file, a executable main target file should be generated.
 
+[[ -x ./build.sh ]] || {
+    echo "Missing a executable build script: build.sh"; exit 1
+}
+
+./build.sh || exit 1
+
+# configure environment variables
 [[ -f .env ]] && source .env
-. build.sh && ./main $*
-status=$?
+[[ -x ./main ]] || {
+    echo "Missing a executable target file: ./main"; exit 1
+}
 
-if [[ $status -eq 0 ]]; then
-    echo "Process exited normally"
-else
-    echo "Process exited with code: ${status}"
-fi
+./main "$@" || {
+    status=$?; echo "Process exited with code: ${status}"; exit "${status}"
+}
 
-exit $status
+exit 0
diff --git a/script/mufzf b/script/mufzf
--- a/script/mufzf
+++ b/script/mufzf
@@ -2,16 +2,62 @@
 
 # `if else fi` indentation in vim is cursed
 
+version=$(tmux -V | awk '{ print $2; }')
+read -r gt_version <<< "$(printf '%s\n%s\n' 3.3 "$version" | sort --reverse)"
+[[ $gt_version = "$version" ]] && fzf_flag+=(--tmux='center,90%')
+
 [[ -z $session_path ]] && session_path="$HOME/.local/state/mufzf/session"
 
-# -i: increament to existing session
+find_cmd=(
+    find .
+    -maxdepth 1
+    -type f
+    -not -path '*/.*'
+    -exec basename {} \;
+)
 
-increament=
+name_sort() { "${find_cmd[@]}" |\
+    sort; }
 
-while getopts "i" opt; do
+date_sort() { "${find_cmd[@]}" |\
+    xargs -I{} sh -c "stat --printf='%Y %n\n' {}" |\
+    sort --reverse |\
+    awk '{ $1=""; print $0; }' |\
+    awk '{ $1=$1; print; }'; }
+
+# -i: increment to existing session
+
+increment=
+sort_method=name_sort
+
+# PREVIEW='file {}'
+# [[ $TERMINAL = wezterm ]] && which ebook-getcover &> /dev/null\
+#     && PREVIEW='magick -- {}\[0\] PNG:- 2> /dev/null\
+#     | chafa \
+#     --clear\
+#     -f sixels\
+#     -s ${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}\
+#     --passthrough=tmux\
+#     2> /dev/null\
+#     '\
+
+while getopts "is:" opt; do
     case $opt in
         i)
-            increament=1
+            increment=1
+            ;;
+        s)
+            case $OPTARG in
+                name)
+                    # sort_method=name_sort
+                    ;;
+                date)
+                    sort_method=date_sort
+                    ;;
+                *)
+                    echo "unknown method $OPTARG" >&2; exit 1
+                    ;;
+            esac
             ;;
         \?)
             echo "Invalid option: -$OPTARG" >&2
@@ -22,35 +68,44 @@ done
 shift $((OPTIND - 1))
 
 workspace=${1:-$(i3-msg -t get_workspaces | jq -r '.[] | select(.focused==true).name')}
-! [[ -d $(dirname "$session_path") ]] && mkdir -p "$(dirname "$session_path")"
+[[ -d $(dirname "$session_path") ]] || mkdir -p "$(dirname "$session_path")"
 
 [[ -t 0 ]] || read -r -d '' select
-[[ -t 0 ]] && select=$(find . -maxdepth 1 -not -path '*/.*' -type f -exec basename {} \;\
-    | grep -E "\.pdf$|\.epub$"\
-    | fzf -m --cycle\
-    --bind ctrl-l:toggle\
-    --bind ctrl-h:cancel\
-)
+[[ -t 0 ]] && select=$("${find_cmd[@]}" |\
+    /bin/grep -E "\.pdf$|\.epub$" |\
+    fzf -m --cycle\
+    --bind 'ctrl-l:toggle'\
+    --bind 'ctrl-h:execute(nohup zathura {} &> /dev/null & disown)'\
+    --bind 'ctrl-d:page-down'\
+    --bind 'ctrl-u:page-up'\
+    "${fzf_flag[@]}")
 
-[[ -z $increament ]] && : > "$session_path"
-
+[[ -z $increment ]] && : > "$session_path"
 [[ -z $select ]] && exit 1
 
-i3-msg "workspace $workspace" > /dev/null || {
-    echo "Failed to swap to workspace $workspace" >&2 && exit 1
-}
+switch_workspace=
+# i3-msg "workspace $workspace" > /dev/null || {
+#     echo "Failed to swap to workspace $workspace" >&2 && exit 1
+# }
 
 while read -r file; do
     [[ -r $file ]] || continue
+
+    [[ -z $switch_workspace ]] && {
+        switch_workspace=1; i3-msg "workspace $workspace"\
+        > /dev/null\
+        || { echo "Failed to swap to workspace $workspace" >&2; exit 1; }
+    }
 
     nohup zathura "$file"\
         &> /dev/null & disown || {
         echo "Failed to open '$file'" && continue
     }
 
-    [[ -t 1 ]] && echo "$PWD/$file" >> "$session_path"
+    [[ -t 1 ]] && echo "$PWD/$file" | tee -a "$session_path"
     [[ -t 1 ]] || echo "$PWD/$file"
-
 done <<< "$select"
+
+[[ -n $dry_run ]] && { echo "session file:"; cat "$session_path"; }
 
 exit 0
diff --git a/script/projnew b/script/projnew
--- a/script/projnew
+++ b/script/projnew
@@ -5,14 +5,21 @@ show_info=false # -i
 recipe= # <cmd> [<option>] <recipe>
 pager=$(which glow) || pager=less
 only_list=false
+update=none
 
-while getopts "hil" opt; do
+excludes=(
+    .info
+    .exec
+)
+
+while getopts "hilo" opt; do
     case $opt in
         h)
             echo "copy files from templates and execute custom script to setup a project"
             echo "-h: show this help"
             echo "-i: show recipe info if available"
             echo "-l: list available recipes"
+            echo "-o: overwrite existing files"
             exit 0
             ;;
         i)
@@ -20,6 +27,9 @@ while getopts "hil" opt; do
             ;;
         l)
             only_list=true # list available recipes
+            ;;
+        o)
+            update=older
             ;;
         \?)
             echo "Invalid option: -$OPTARG" >&2; exit 1
@@ -49,18 +59,19 @@ fi
 echo "Copying template files..."
 while read -r file; do
     fname=${file#"$template"/"$recipe"/}
-    if [[ $fname == .info ]]; then
+    if [[ " ${excludes[*]} " =~ [[:space:]]${fname}[[:space:]] ]]; then
         continue
-    elif [[ $fname == .exec ]]; then
-        echo "Custom script found, executing..."
-        eval . "$template/$recipe/.exec" || {
-            echo "errors occurred during execution of the custom script" && exit 1
-        }
     else
         # echo $fname
         [[ -d $(dirname "$fname") ]] || mkdir -p "$(dirname "$fname")"
-        [[ -f $file ]] && cp --update --preserve=links "$file" "$fname"
+        [[ -f $file ]] && cp --update=$update --preserve=links "$file" "$fname"
     fi
 done <<< "$(find -L $template/"$recipe"/ -type f)"
+
+[[ -f "$template/$recipe/.exec" ]] && (
+echo "Custom script found, executing..."; "$template/$recipe/.exec" || {
+    echo "errors occurred during execution of the custom script"; exit 1
+}
+)
 
 echo "Project setup completed"
