webpack-express template + nvim configs
	modified:   nvim/config/conform-nvim.lua
	modified:   nvim/config/lspconfig.lua
	new file:   nvim/ftplugin/tpl.lua
	modified:   script/mufzf
	modified:   script/projnew
	new file:   script/template/webpack-express/.exec
	new file:   script/template/webpack-express/.gitignore
	new file:   script/template/webpack-express/.info
	new file:   script/template/webpack-express/public/favicon.ico
	new file:   script/template/webpack-express/server.js
	new file:   script/template/webpack-express/src/components/App.js
	new file:   script/template/webpack-express/src/components/Main.js
	new file:   script/template/webpack-express/src/index.js
	new file:   script/template/webpack-express/src/styles/main.css
	new file:   script/template/webpack-express/webpack.config.js

diff --git a/script/mufzf b/script/mufzf
--- a/script/mufzf
+++ b/script/mufzf
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-# A satisfactory and elegant script for those who really love reading books.
-
 select=$(
 find . -maxdepth 1 -not -path '*/.*' -type f -exec basename {} \;\
 	| grep -E "\.pdf$|\.epub$"\
@@ -10,11 +8,16 @@ find . -maxdepth 1 -not -path '*/.*' -type f -exec basename {} \;\
 	--bind ctrl-h:cancel
 )
 
-[[ -z $select ]] && exit 0
+[[ -z $select ]] && exit 1
 
 workspace=${1:-$(i3-msg -t get_workspaces | jq -r '.[] | select(.focused==true).name')}
 i3-msg "workspace $workspace" > /dev/null || exit 1
 
 while read -r file; do
-	nohup zathura "$file" &> /dev/null & disown || exit 1
-done <<< $select
+    nohup zathura "$file"\
+        &> /dev/null & disown || {
+        echo "Failed to open '$file'" && continue
+    }
+done <<< "$select"
+
+exit 0
diff --git a/script/projnew b/script/projnew
--- a/script/projnew
+++ b/script/projnew
@@ -4,13 +4,7 @@ template=/usr/share/projnew/template
 show_info=false # -i
 recipe= # <cmd> [<option>] <recipe>
 pager=$(which glow) || pager=less
-pager_option=
 only_list=false
-
-panic() {
-    while [[ ! -z $1 ]]; do echo $1; shift 1; done
-    exit 1
-}
 
 while getopts "hil" opt; do
     case $opt in
@@ -32,7 +26,7 @@ while getopts "hil" opt; do
             ;;
     esac
 done
-shift $(($OPTIND - 1))
+shift $((OPTIND - 1))
 
 recipe=${1:-c}
 
@@ -40,31 +34,34 @@ recipe=${1:-c}
 
 if $only_list; then
     echo "Available recipes:"
-    for list_recipe in $(ls $template); do
-        printf "\t%s\n" $list_recipe
+    for list_recipe in "$template"/*; do
+        printf "\t%s\n" "$list_recipe"
     done
     exit 0
 elif $show_info; then
     if [[ -f $template/$recipe/.info ]]; then
-        echo "recipe \'$recipe\':" && $pager $template/$recipe/.info && exit 0
+        printf "recipe \'%s\':\n" "$recipe" && $pager $template/"$recipe"/.info && exit 0
     else
-        echo No available info regarding recipe \'$recipe\' && exit 1
+        printf "No available info regarding recipe \'%s\'\n" "$recipe" && exit 1
     fi
 fi
 
 echo "Copying template files..."
 while read -r file; do
-    fname=${file#$template/$recipe/}
+    fname=${file#"$template"/"$recipe"/}
     if [[ $fname == .info ]]; then
+        which glow &>/dev/null && glow "$file"
         continue
     elif [[ $fname == .exec ]]; then
         echo "Custom script found, executing..."
-        . $template/$recipe/.exec || panic "errors occurred during execution of the custom script"
+        eval . "$template/$recipe/.exec" || {
+            echo "errors occurred during execution of the custom script" && exit 1
+        }
     else
         # echo $fname
-        [[ -d $(dirname $fname) ]] || mkdir -p $(dirname $fname)
-        [[ -f $file ]] && cp --update --preserve=links $file $fname
+        [[ -d $(dirname "$fname") ]] || mkdir -p "$(dirname "$fname")"
+        [[ -f $file ]] && cp --update --preserve=links "$file" "$fname"
     fi
-done <<< $(find -L $template/$recipe/ -type f)
+done <<< "$(find -L $template/"$recipe"/ -type f)"
 
 echo "Project setup completed"
