modified:   nvim/config/global_conf.lua 	modified:   script/projnew 	modified:   wezterm/wezterm.lua 	modified:   zsh

diff --git a/script/projnew b/script/projnew
--- a/script/projnew
+++ b/script/projnew
@@ -3,9 +3,11 @@
 template=/usr/share/projnew/template
 recipe=${1:-c}
 
+[[ -d $template/$recipe ]] || { echo "Recipe $recipe not found"; exit 1; }
+
 while read -r file; do
-    fname=${file%$template/$recipe/}
-    echo $fname
+    fname=${file#$template/$recipe/}
+    # echo $fname
     [[ -d $(dirname $fname) ]] || mkdir -p $(dirname $fname)
-    [[ -f $file ]] && cp --update $file ./
+    [[ -f $file ]] && cp --update $file $fname
 done <<< $(find $template/$recipe -type f)
